export interface Tech {
  name: string;
  since: string;
}

function tech(name: string, since: string): Tech {
  return { name, since };
}

export const backend = {
  nodejs: tech("Node.js", "2012"),
  java: tech("Java", "2008"),
  kotlin: tech("Kotlin", "2016"),
  csharp: tech("C#", "2018"),
  python: tech("Python", "2018"),
  r: tech("R", "2018"),
  mysql: tech("MySQL", "2013"),
  postgresql: tech("PostgreSQL", "2013"),
  mongodb: tech("MongoDB", "2018"),
  prisma: tech("Prisma", "2021"),
  redis: tech("Redis", "2015"),
  graphql: tech("GraphQL", "2021"),
  rest: tech("REST", "2012"),
  websockets: tech("WebSockets", "2016"),
  express: tech("Express", "2012"),
  typegraphql: tech("TypeGraphQL", "2021"),
  apollo: tech("Apollo", "2021"),
  jersey: tech("Jersey", "2020"),
  jdbc: tech("JDBC", "2020"),
  paypal: tech("PayPal", "2016"),
  elasticsearch: tech("ElasticSearch", "2019"),
  docker: tech("Docker", "2016"),
  aws: tech("AWS", "2013"),
  ecs: tech("ECS", "2016"),
  s3: tech("S3", "2015"),
  sns: tech("SNS", "2015"),
  sqs: tech("SQS", "2015"),
  cicd: tech("CI/CD", "2018"),
  githubActions: tech("GitHub Actions", "2020"),
  microservices: tech("Microservices", "2019"),
  distributedSystems: tech("Distributed Systems", "2019"),
  solutionArchitecture: tech("Solution Architecture", "2016"),
} as const;

export const frontend = {
  javascript: tech("JavaScript", "2008"),
  typescript: tech("TypeScript", "2016"),
  reactjs: tech("React.js", "2016"),
  nextjs: tech("Next.js", "2021"),
  tailwind: tech("Tailwind", "2020"),
  vue2: tech("Vue 2", "2017"),
  sveltekit: tech("SvelteKit", "2023"),
  angular: tech("Angular", "2021"),
  jquery: tech("JQuery", "2010"),
  backbone: tech("Backbone", "2011"),
  electronjs: tech("Electron.js", "2021"),
  chakraUi: tech("Chakra UI", "2020"),
  reactQuery: tech("React Query", "2021"),
  reduxToolkit: tech("Redux Toolkit", "2021"),
  echarts: tech("ECharts", "2019"),
  valtio: tech("Valtio", "2022"),
  vite: tech("Vite", "2022"),
  jest: tech("Jest", "2018"),
  playwright: tech("Playwright", "2023"),
  storybook: tech("Storybook", "2020"),
  urql: tech("URQL", "2021"),
  reactHookForm: tech("React Hook Form", "2020"),
  lighthouse: tech("Lighthouse", "2019"),
} as const;

export const mobile = {
  android: tech("Android", "2010"),
  ios: tech("iOS", "2014"),
  xamarin: tech("Xamarin", "2014"),
  reactNative: tech("React Native", "2021"),
} as const;

export const blockchain = {
  ethereum: tech("Ethereum", "2020"),
  evm: tech("EVM", "2020"),
  web3: tech("Web3", "2018"),
  blockchain: tech("Blockchain", "2020"),
  smartContracts: tech("Smart Contracts", "2018"),
  solidity: tech("Solidity", "2020"),
  foundry: tech("Foundry", "2025"),
  hardhat: tech("Hardhat", "2020"),
  protocolArchitecture: tech("Protocol Architecture", "2023"),
  fuzzing: tech("Fuzzing", "2023"),
  gasOptimization: tech("Gas Optimization", "2023"),
  wagmi: tech("Wagmi", "2023"),
  viem: tech("Viem", "2024"),
  theGraph: tech("The Graph", "2023"),
  ethers: tech("Ethers", "2021"),
  solana: tech("Solana", "2021"),
  flow: tech("Flow", "2022"),
  cadence: tech("Cadence", "2022"),
  neoN3: tech("Neo N3", "2021"),
  vmCompilerDevelopment: tech("VM Compiler Development", "2018"),
  walletDevelopment: tech("Wallet Development", "2021"),
  walletInfrastructure: tech("Wallet Infrastructure", "2021"),
  walletConnect: tech("WalletConnect", "2021"),
  multiChainIntegration: tech("Multi-chain Integration", "2018"),
  sdkDevelopment: tech("SDK Development", "2022"),
  cryptography: tech("Cryptography", "2023"),
  accountAbstraction: tech("Account Abstraction", "2024"),
  nft: tech("NFT", "2018"),
  cryptoCurrency: tech("Crypto Currency", "2018"),
  dex: tech("DEX", "2021"),
  amm: tech("AMM", "2023"),
  auditPrep: tech("Audit Prep", "2023"),
  slither: tech("Slither", "2023"),
  automatedTesting: tech("Automated Testing", "2020"),
  systemArchitecture: tech("System Architecture", "2025"),
  uniswapV3: tech("Uniswap V3", "2025"),
  uniswapV4: tech("Uniswap V4", "2025"),
  predictionMarket: tech("Prediction Market", "2026"),
  vault: tech("Vault", "2026"),
  clob: tech("CLOB", "2026"),
  optimism: tech("Optimism", "2025"),
} as const;

export const ai = {
  aiProcessAutomation: tech("AI Process Automation", "2025"),
  agentDevelopment: tech("Agent Development", "2025"),
  mcp: tech("MCP", "2025"),
  claudeSkills: tech("Claude Skills", "2025"),
  harnessEngineering: tech("Harness Engineering", "2026"),
  specDrivenDevelopment: tech("Spec-Driven Development", "2025"),
  claude: tech("Claude", "2025"),
  anthropicApi: tech("Anthropic API", "2025"),
  openaiApi: tech("OpenAI API", "2023"),
  claudeCode: tech("Claude Code", "2025"),
  cursor: tech("Cursor", "2024"),
  contextEngineering: tech("Context Engineering", "2025"),
  agenticWorkflows: tech("Agentic Workflows", "2025"),
  evals: tech("Evals", "2025"),
  rag: tech("RAG", "2024"),
  aiTooling: tech("AI Tooling", "2025"),
} as const;
